export const pagination ={
     data:[
         {
             id:1,
             image:'https://img.freepik.com/premium-vector/taxi-app-illustrated_23-2148506376.jpg?size=626&ext=jpg',
             heading:'Discover the Marvels of Our World: The New Seven Wonders',
             location:'https://cdn-icons-png.flaticon.com/512/9088/9088666.png',
             text1:'Traveling and exploring the world has always been a passion for many, and what better way to do so than to',
             text2:'witness some of the greatest marvels our world has to offer. The New Seven Wonders of the World are a list',
             text3:'of seven breathtaking structures, chosen from a list of 200, that showcase the talent, creativity, and technical',
             text4:'prowess of humanity.',
             button:'Read more',
         },
         {  
            id:2,
            image:'https://img.freepik.com/free-photo/street-night-with-traffic_73683-2253.jpg?size=626&ext=jpg',
            heading:'Discover the Marvels of Our World: The New Seven Wonders',
            location:'https://cdn-icons-png.flaticon.com/512/9088/9088666.png',
            text1:'Traveling and exploring the world has always been a passion for many, and what better way to do so than to',
            text2:'witness some of the greatest marvels our world has to offer. The New Seven Wonders of the World are a list',
            text3:'of seven breathtaking structures, chosen from a list of 200, that showcase the talent, creativity, and technical',
            text4:'prowess of humanity.',
            button:'Read more',
        },
        {
            id:3,
            image:'https://img.freepik.com/free-photo/close-up-shot-taxi-sign-warm-colours-sunset-with-bokeh-lights-background_181624-54985.jpg?size=626&ext=jpg',
            heading:'Discover the Marvels of Our World: The New Seven Wonders',
            location:'https://cdn-icons-png.flaticon.com/512/9088/9088666.png',
            text1:'Traveling and exploring the world has always been a passion for many, and what better way to do so than to',
            text2:'witness some of the greatest marvels our world has to offer. The New Seven Wonders of the World are a list',
            text3:'of seven breathtaking structures, chosen from a list of 200, that showcase the talent, creativity, and technical',
            text4:'prowess of humanity.',
            button:'Read more',
        },
        {
            id:4,
            image:'https://img.freepik.com/free-photo/smiley-businesswoman-driving-her-car-looking-side-mirror_23-2148767008.jpg?size=626&ext=jpg',
            heading:'Discover the Marvels of Our World: The New Seven Wonders',
            location:'https://cdn-icons-png.flaticon.com/512/9088/9088666.png',
            text1:'Traveling and exploring the world has always been a passion for many, and what better way to do so than to',
            text2:'witness some of the greatest marvels our world has to offer. The New Seven Wonders of the World are a list',
            text3:'of seven breathtaking structures, chosen from a list of 200, that showcase the talent, creativity, and technical',
            text4:'prowess of humanity.',
            button:'Read more',
        },
        {  
            id:5,
            image:'https://img.freepik.com/free-vector/young-tourists-with-backpacks-standing-near-road-hitchhiking-isolated-flat_74855-13747.jpg?size=626&ext=jpg',
            heading:'Discover the Marvels of Our World: The New Seven Wonders',
            location:'https://cdn-icons-png.flaticon.com/512/9088/9088666.png',
            text1:'Traveling and exploring the world has always been a passion for many, and what better way to do so than to',
            text2:'witness some of the greatest marvels our world has to offer. The New Seven Wonders of the World are a list',
            text3:'of seven breathtaking structures, chosen from a list of 200, that showcase the talent, creativity, and technical',
            text4:'prowess of humanity.',
            button:'Read more',
        },
        {
            id:6,
            image:'https://img.freepik.com/premium-vector/taxi-app-concept-with-mobile-phone-city_23-2148503823.jpg?size=626&ext=jpg',
            heading:'Discover the Marvels of Our World: The New Seven Wonders',
            location:'https://cdn-icons-png.flaticon.com/512/9088/9088666.png',
            text1:'Traveling and exploring the world has always been a passion for many, and what better way to do so than to',
            text2:'witness some of the greatest marvels our world has to offer. The New Seven Wonders of the World are a list',
            text3:'of seven breathtaking structures, chosen from a list of 200, that showcase the talent, creativity, and technical',
            text4:'prowess of humanity.',
            button:'Read more',
        },
        {
            id:7,
            image:'https://img.freepik.com/premium-photo/businesswoman-sitting-drivers-seat-her-car-using-phone_255667-32.jpg?size=626&ext=jpg',
            heading:'Discover the Marvels of Our World: The New Seven Wonders',
            location:'https://cdn-icons-png.flaticon.com/512/9088/9088666.png',
            text1:'Traveling and exploring the world has always been a passion for many, and what better way to do so than to',
            text2:'witness some of the greatest marvels our world has to offer. The New Seven Wonders of the World are a list',
            text3:'of seven breathtaking structures, chosen from a list of 200, that showcase the talent, creativity, and technical',
            text4:'prowess of humanity.',
            button:'Read more',
        },
        {
            id:8,
            image:'https://img.freepik.com/free-vector/taxi-service-infographics_1284-11015.jpg?size=626&ext=jpg',
            heading:'Discover the Marvels of Our World: The New Seven Wonders',
            location:'https://cdn-icons-png.flaticon.com/512/9088/9088666.png',
            text1:'Traveling and exploring the world has always been a passion for many, and what better way to do so than to',
            text2:'witness some of the greatest marvels our world has to offer. The New Seven Wonders of the World are a list',
            text3:'of seven breathtaking structures, chosen from a list of 200, that showcase the talent, creativity, and technical',
            text4:'prowess of humanity.',
            button:'Read more',
        },
        {
            id:9,
            image:'https://img.freepik.com/free-photo/black-yellow-sign-taxi-night-placed-top-car_181624-17433.jpg?size=626&ext=jpg',
            heading:'Discover the Marvels of Our World: The New Seven Wonders',
            location:'https://cdn-icons-png.flaticon.com/512/9088/9088666.png',
            text1:'Traveling and exploring the world has always been a passion for many, and what better way to do so than to',
            text2:'witness some of the greatest marvels our world has to offer. The New Seven Wonders of the World are a list',
            text3:'of seven breathtaking structures, chosen from a list of 200, that showcase the talent, creativity, and technical',
            text4:'prowess of humanity.',
            button:'Read more',
        },
        {
            id:10,
            image:'https://img.freepik.com/free-vector/gps-navigation-set-icons_24877-51540.jpg?size=626&ext=jpg',
            heading:'Discover the Marvels of Our World: The New Seven Wonders',
            location:'https://cdn-icons-png.flaticon.com/512/9088/9088666.png',
            text1:'Traveling and exploring the world has always been a passion for many, and what better way to do so than to',
            text2:'witness some of the greatest marvels our world has to offer. The New Seven Wonders of the World are a list',
            text3:'of seven breathtaking structures, chosen from a list of 200, that showcase the talent, creativity, and technical',
            text4:'prowess of humanity.',
            button:'Read more',
        },
        
     ]
 }