export const pagination ={
     data:[
         {
             id:1,
             image:'https://img.freepik.com/free-photo/restaurant-hall-with-red-brick-walls-wooden-tables-pipes-ceiling_140725-8504.jpg?size=626&ext=jpg',
             heading:'Discover the Marvels of Our World: The New Seven Wonders',
             location:'https://cdn-icons-png.flaticon.com/512/9088/9088666.png',
             text1:'Traveling and exploring the world has always been a passion for many, and what better way to do so than to',
             text2:'witness some of the greatest marvels our world has to offer. The New Seven Wonders of the World are a list',
             text3:'of seven breathtaking structures, chosen from a list of 200, that showcase the talent, creativity, and technical',
             text4:'prowess of humanity.',
             button:'Read more',
         },
         {  
            id:2,
            image:'https://img.freepik.com/free-photo/hammocks-with-palm-trees_1203-201.jpg?size=626&ext=jpg',
            heading:'Discover the Marvels of Our World: The New Seven Wonders',
            location:'https://cdn-icons-png.flaticon.com/512/9088/9088666.png',
            text1:'Traveling and exploring the world has always been a passion for many, and what better way to do so than to',
            text2:'witness some of the greatest marvels our world has to offer. The New Seven Wonders of the World are a list',
            text3:'of seven breathtaking structures, chosen from a list of 200, that showcase the talent, creativity, and technical',
            text4:'prowess of humanity.',
            button:'Read more',
        },
        {
            id:3,
            image:'https://img.freepik.com/free-photo/landscape-view-leisure-relaxation-summer_1203-4898.jpg?size=626&ext=jpg',
            heading:'Discover the Marvels of Our World: The New Seven Wonders',
            location:'https://cdn-icons-png.flaticon.com/512/9088/9088666.png',
            text1:'Traveling and exploring the world has always been a passion for many, and what better way to do so than to',
            text2:'witness some of the greatest marvels our world has to offer. The New Seven Wonders of the World are a list',
            text3:'of seven breathtaking structures, chosen from a list of 200, that showcase the talent, creativity, and technical',
            text4:'prowess of humanity.',
            button:'Read more',
        },
        {
            id:4,
            image:'https://img.freepik.com/free-photo/young-beauty-blond-woman-having-breakfast-bed-early-morning_23-2148033303.jpg?size=626&ext=jpg',
            heading:'Discover the Marvels of Our World: The New Seven Wonders',
            location:'https://cdn-icons-png.flaticon.com/512/9088/9088666.png',
            text1:'Traveling and exploring the world has always been a passion for many, and what better way to do so than to',
            text2:'witness some of the greatest marvels our world has to offer. The New Seven Wonders of the World are a list',
            text3:'of seven breathtaking structures, chosen from a list of 200, that showcase the talent, creativity, and technical',
            text4:'prowess of humanity.',
            button:'Read more',
        },
        {  
            id:5,
            image:'https://img.freepik.com/free-photo/luxury-pool-villa-spectacular-contemporary-design-digital-art-real-estate-home-house-property-generative-ai-illustration_1258-151616.jpg?size=626&ext=jpg',
            heading:'Discover the Marvels of Our World: The New Seven Wonders',
            location:'https://cdn-icons-png.flaticon.com/512/9088/9088666.png',
            text1:'Traveling and exploring the world has always been a passion for many, and what better way to do so than to',
            text2:'witness some of the greatest marvels our world has to offer. The New Seven Wonders of the World are a list',
            text3:'of seven breathtaking structures, chosen from a list of 200, that showcase the talent, creativity, and technical',
            text4:'prowess of humanity.',
            button:'Read more',
        },
        {
            id:6,
            image:'https://img.freepik.com/premium-photo/luxury-interior-exterior-design-pool-villa-with-livingroom_41487-69.jpg?size=626&ext=jpg',
            heading:'Discover the Marvels of Our World: The New Seven Wonders',
            location:'https://cdn-icons-png.flaticon.com/512/9088/9088666.png',
            text1:'Traveling and exploring the world has always been a passion for many, and what better way to do so than to',
            text2:'witness some of the greatest marvels our world has to offer. The New Seven Wonders of the World are a list',
            text3:'of seven breathtaking structures, chosen from a list of 200, that showcase the talent, creativity, and technical',
            text4:'prowess of humanity.',
            button:'Read more',
        },
        {
            id:7,
            image:'https://img.freepik.com/free-photo/exotic-lunch-hotel-outdoor-shot-table-with-fruits-swimming-pool_197531-20911.jpg?size=626&ext=jpg',
            heading:'Discover the Marvels of Our World: The New Seven Wonders',
            location:'https://cdn-icons-png.flaticon.com/512/9088/9088666.png',
            text1:'Traveling and exploring the world has always been a passion for many, and what better way to do so than to',
            text2:'witness some of the greatest marvels our world has to offer. The New Seven Wonders of the World are a list',
            text3:'of seven breathtaking structures, chosen from a list of 200, that showcase the talent, creativity, and technical',
            text4:'prowess of humanity.',
            button:'Read more',
        },
        {
            id:8,
            image:'https://img.freepik.com/premium-photo/interior-modern-bedroom_123088-12.jpg?size=626&ext=jpg',
            heading:'Discover the Marvels of Our World: The New Seven Wonders',
            location:'https://cdn-icons-png.flaticon.com/512/9088/9088666.png',
            text1:'Traveling and exploring the world has always been a passion for many, and what better way to do so than to',
            text2:'witness some of the greatest marvels our world has to offer. The New Seven Wonders of the World are a list',
            text3:'of seven breathtaking structures, chosen from a list of 200, that showcase the talent, creativity, and technical',
            text4:'prowess of humanity.',
            button:'Read more',
        },
        {
            id:9,
            image:'https://img.freepik.com/free-photo/swimming-pool-with-sun-beds-morning-mediterranean-summer-resort-hotel-turkey-bodrum_627829-7164.jpg?size=626&ext=jpg',
            heading:'Discover the Marvels of Our World: The New Seven Wonders',
            location:'https://cdn-icons-png.flaticon.com/512/9088/9088666.png',
            text1:'Traveling and exploring the world has always been a passion for many, and what better way to do so than to',
            text2:'witness some of the greatest marvels our world has to offer. The New Seven Wonders of the World are a list',
            text3:'of seven breathtaking structures, chosen from a list of 200, that showcase the talent, creativity, and technical',
            text4:'prowess of humanity.',
            button:'Read more',
        },
        {
            id:10,
            image:'https://img.freepik.com/premium-photo/outdoor-swimming-pool-with-counter-bar-pool-terrace_41487-697.jpg?w=996',
            heading:'Discover the Marvels of Our World: The New Seven Wonders',
            location:'https://cdn-icons-png.flaticon.com/512/9088/9088666.png',
            text1:'Traveling and exploring the world has always been a passion for many, and what better way to do so than to',
            text2:'witness some of the greatest marvels our world has to offer. The New Seven Wonders of the World are a list',
            text3:'of seven breathtaking structures, chosen from a list of 200, that showcase the talent, creativity, and technical',
            text4:'prowess of humanity.',
            button:'Read more',
        },
        
     ]
 }